import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  admin: [
    // users
    PERMISSIONS.USER.CREATE,
    PERMISSIONS.USER.VIEW,
    PERMISSIONS.USER.UPDATE,
    PERMISSIONS.USER.DELETE,

    // category
    PERMISSIONS.CATEGORY.CREATE,
    PERMISSIONS.CATEGORY.VIEW,
    PERMISSIONS.CATEGORY.UPDATE,
    PERMISSIONS.CATEGORY.DELETE,

    // subcategory
    PERMISSIONS.SUBCATEGORY.CREATE,
    PERMISSIONS.SUBCATEGORY.VIEW,
    PERMISSIONS.SUBCATEGORY.UPDATE,
    PERMISSIONS.SUBCATEGORY.DELETE,

    // product
    PERMISSIONS.PRODUCT.CREATE,
    PERMISSIONS.PRODUCT.VIEW,
    PERMISSIONS.PRODUCT.UPDATE,
    PERMISSIONS.PRODUCT.DELETE,
  ],
} as const;
